spring:
  application:
    name: simple-wg-ad-dev
  thymeleaf:
    cache: false
    prefix: file:src/main/resources/templates/
logging:
  level:
    com.leojay.simplewgad.service : DEBUG

wg-manager:
  default:
    server-ip: localhost
  peer-meta-data:
    path: "data/"
