spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  web:
    locale: en_US
  thymeleaf:
    prefix: classpath:/static/


logging:
  config: classpath:logback-spring.xml
  level:
    org.springframework.web : INFO

wg-manager:
  default:
    interface-name: wg0 #管理页面在启动时会去查找这个接口的信息
    server-private-key: your_private_key
    listen-port: 51280
    bash-path: /opt/homebrew/bin/bash #wg-quick似乎需要4.0往上,部分主机默认的bash可能版本过低

