[Interface]
# 填入你刚才生成的 privatekey 内容
PrivateKey = GCNL0542D7pOCrRuuUQ+TXJO+FhCLP52oZ9JYV7U5Ug=
# 客户端在隧道内的虚拟 IP
Address = 10.0.0.2/24
# 可选：指定 DNS 防止泄露
DNS = 8.8.8.8

[Peer]
# 填入服务端的公钥
PublicKey = O5aBjaJXHuCKzePxy+bcAoupxUuFU4508u1sdluIgzU=
# 允许通过隧道的流量（0.0.0.0/0 表示全局代理）
AllowedIPs = 0.0.0.0/0
# 服务端的公网 IP 和端口
Endpoint = 1.2.3.4:51820
# 保持 NAT 穿透连接（建议开启）
PersistentKeepalive = 25
