[Interface]
PrivateKey = GCNL0542D7pOCrRuuUQ+TXJO+FhCLP52oZ9JYV7U5Ug=
Address = 10.0.0.2/24
DNS = 8.8.8.8

[Peer]
PublicKey = O5aBjaJXHuCKzePxy+bcAoupxUuFU4508u1sdluIgzU=
AllowedIPs = 0.0.0.0/0
Endpoint = 1.2.3.4:51820
PersistentKeepalive = 25
